version: 2
jobs:
    build:
        working_directory: ~/workspace
        docker:
            - image: node
        steps:
            - checkout
            - run:
                name: version infomation
                command: |
                    echo "Node $(node -v)"
                    echo "yarn $(yarn --version)"

            - run:
                name: Install dependencies
                command: yarn
            - run :
                name: process exit successfly
                command: |
                    node -e " \
                             console.log('hello world');\
                             process.exit(0);"

            - run :
                name: process exit with volkswagen
                command: |
                    node -e " \
                             require('volkswagen');\
                             console.log('hello world');\
                             process.exit(1);"
            - run :
                name: process exit with error code
                command: |
                    node -e " \
                             console.log('hello world');\
                             process.exit(1);"

